# Generated by Django 5.1.5 on 2025-03-17 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ArtistInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=255, null=True)),
                ("Id_number", models.IntegerField(blank=True, null=True)),
                ("Genres", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Image",
                    models.FileField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="MovieInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Image",
                    models.FileField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                ("Id_number", models.IntegerField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="SongInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=255, null=True)),
                ("Artists", models.CharField(blank=True, max_length=255, null=True)),
                ("Movie", models.CharField(blank=True, max_length=255, null=True)),
                ("Track", models.FileField(blank=True, null=True, upload_to="")),
                ("Picture", models.FileField(blank=True, null=True, upload_to="")),
            ],
        ),
        migrations.CreateModel(
            name="TrackModel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=255)),
                ("url", models.URLField()),
            ],
        ),
        migrations.CreateModel(
            name="AlbumInformation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("Title", models.CharField(blank=True, max_length=255, null=True)),
                ("Artists", models.CharField(blank=True, max_length=255, null=True)),
                ("Movie", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "Image",
                    models.FileField(
                        blank=True, max_length=255, null=True, upload_to=""
                    ),
                ),
                ("Tracks", models.ManyToManyField(to="s_backend.trackmodel")),
            ],
        ),
    ]
