# Generated by Django 5.1.5 on 2025-03-17 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("s_backend", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="songinformation",
            name="Id_number",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
